#CC65_HOME=/home/lint/Snes/cc65
#CC65_BIN=$(CC65_HOME)/bin

#SFCLIB_PATH=/home/lint/Dropbox/Snes/projects/Snes_Tools/sfclib/bin
#CFG_PATH=/home/lint/Dropbox/Snes/projects/Snes_Tools/sfclib/cfg

CC65_HOME=/Users/lint/Dropbox/Snes/projects/Snes_Tools/cc65
CC65_BIN=$(CC65_HOME)/bin

SFCLIB_PATH=/Users/lint/Dropbox/Snes/projects/Snes_Tools/sfclib/bin
CFG_PATH=/Users/lint/Dropbox/Snes/projects/Snes_Tools/sfclib/cfg