include Makefile.inc

all clean:
	@$(MAKE) -C color $@
	@$(MAKE) -C hello $@
	@$(MAKE) -C joypad $@
	@$(MAKE) -C splash $@
	@$(MAKE) -C scroll $@
	@$(MAKE) -C dual $@
	@$(MAKE) -C hdma $@
	@$(MAKE) -C sprite $@
