include Makefile.inc

all clean:
	@$(MAKE) -C color $@
	@$(MAKE) -C hello $@
	@$(MAKE) -C joypad $@
	@$(MAKE) -C scroll $@
	@$(MAKE) -C scrollOptimized $@
	@$(MAKE) -C dual $@
	@$(MAKE) -C hdma $@
	@$(MAKE) -C hdmaRipple $@
	@$(MAKE) -C metasprite $@
	# @$(MAKE) -C metaspriteOptimized $@
	@$(MAKE) -C splash $@
	@$(MAKE) -C sprite $@
	@$(MAKE) -C spriteIRQTrick $@
	@$(MAKE) -C transparency $@
